version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '3002:3002'
    env_file:
      - ./apps/api/.env

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - '3003:3003'
    depends_on:
      - api
    env_file:
      - ./apps/web/.env